version: '3'

services:

  backend:
    build: ./app
    restart: always
    ports:
      - 8000:8000
    # volumes:
    #   - ./app:/usr/src/app
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.32
    restart: always
    container_name: db_mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: snippetbox
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # - .\db_scripts:/docker-entrypoint-initdb.d

volumes:
  mysql_data: