version: '3'

services:

  backend:
    build: ./app
    restart: always
    ports:
      - 8000:8000
    # volumes:
    #   - ./app:/usr/src/app
    depends_on:
      - db_mysql


  db_mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: root2
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: snippetbox
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # - .\db_scripts:/docker-entrypoint-initdb.d
    # healthcheck:
    #   test: ["CMD", "mysql" ,"-u", "root2", "-p", "password"]
    #   timeout: 20s
    #   retries: 10

volumes:
  mysql_data: