version: '3'

services:

  # backend:
  #   build: ./app
  #   restart: always
  #   ports:
  #     - "4000:4000"
  #   volumes:
  #     - ./backend:/app
    # environment: 
    #   - CHOKIDAR_USEPOLLING=true
    #   - MYSQL_HOST=mysql
    #   - MYSQL_USER=root
    #   - MYSQL_PORT=3306
    #   - MYSQL_PASSWORD=password
    #   - MYSQL_DB=snippetbox
    # depends_on:
    #   - mysql

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: snippetbox
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # - .\db_scripts:/docker-entrypoint-initdb.d

volumes:
  mysql_data: